config/routes.rb
SdTeam::Application.routes.draw do

  resources :blogs do
    resources :comments, :only => [ :create ]
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	attr_accessible :body, :title

	has_many :comments

	validates_presence_of :body, :title
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate, :except => [ :index, :show ]
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
  def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == "admin" && password == "sdteamsecret"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@blog = Blog.find(params[ :blog_id ])
		@comment = @blog.comments.create!(params[ :comment ])
		redirect_to @blog
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_blog.html.erb
<h2><%= link_to_unless_current blog.title, blog %></h2>
<%= simple_format blog.body %>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<%= render :partial => @blogs %>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => @blog %>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

<h2>Comments</h2>
<div class="blog-comment">
	<%= render :partial => @blog.comments %>
</div>

<%= form_for [@blog, Comment.new] do |f| %>
	<p>
		<%= f.label :body, "New Comment" %><br/>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit "Add Comment" %>
	</p>
<% end %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<p>
		<strong>Posted <%= time_ago_in_words(comment.created_at) %> ago</strong>
		<br/>
		<%= comment.body %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SdTeam</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>